### PR TITLE
change repo location url

### LINKED ISSUE #34: Change install.sh to use new repo location

### PR DESCRIPTION
**Pull request by sbtaylor15**
Fixes #34
Fixes pyrsia/pyrsia#605
Fixes pyrsia/pyrsia#578

Separate PR will update the website doc since those changes are on the main branch.

### CODE REVIEW

**Comment by johanvos** [comment]
I don't see content at https://repo.pyrsia.io/repos ?

**Review by erwin1 — APPROVED** [review]

**Comment by prince-chrismc** [comment]
How do you feel about moving this to the main Repo and copying it in? it's been a few times it's gotten deleted being a branch that's periodically getting flushed with no trace else where

**Comment by prince-chrismc** [comment]
GitHub having issues with linked issues 🤔 

image

**Comment by sbtaylor15** [comment]
> How do you feel about moving this to the main Repo and copying it in? it's been a few times it's gotten deleted being a branch that's periodically getting flushed with no trace else where

I think keeping it together in the GCS will be best.  That way it will be easier to keep in sync with the .deb files that use it as part of the signing verification. 

GCS should not have the issue with stuff going missing since it is outside of GH branches.

**Comment by prince-chrismc** [comment]
> GCS

What is GCS? I assume Google Cloud Stuff 😆 

> I think keeping it together in the GCS will be best.

I think that's an excellent idea! I like to keep "code" in a repo but I think your suggestion elevates the issue we've been hitting so I am good with that

**Comment by sbtaylor15** [comment]
> > GCS
> 
> What is GCS? I assume Google Cloud Stuff 😆
> 
> > I think keeping it together in the GCS will be best.
> 
> I think that's an excellent idea! I like to keep "code" in a repo but I think your suggestion elevates the issue we've been hitting so I am good with that

GCS = Google Cloud Storage.  We can get fancy down the road and have it stored in multiple google regions for redundancy

**Review by prince-chrismc — APPROVED** [review]
Let's move forward

**Pull request merged**
